export const AppString = {
    login: "Login",
    create_account: "Create Your Account",
    join_us: "Join us and start organizing your tasks today!",
    register: "Register",
    already_account: "Already have an account?",
    sign_in: "Sign In",
    welcomeback: "Welcome!",
    sign_In_access: "Sign to access your tasks and stay productive",
    forget_password: "Forgot your password?",
    reset_here: "Reset  it here",
    do_not_have_account: "Don't have an account?",
    sing_up: "Sign Up",
    enter_name: "Enter Your Full Name",
    enter_email: "Enter Your Email",
    enter_password: "Enter Your Password",
    enter_confirm_password: "Confirm Password",
    get_tasks_done: "Gets Tasks Done with ToDo",
    your_app_organized: "Your to-do app to stay organized, set priorities, and achieve goals effortlessly.",
    get_started: "Get Started",
    password_recovery: "Password recovery",
    fill_register_email: "Please fill in an email you used on registration. We'll send you a confirmation code.",
    add_new_task: "New List",
    new_task: "Add a Task",
    enter_title: "Enter a Title",
    enter_description: "Enter a Description",
    add:"Add",
    cancel: "Cancel",
    ok: "Ok",
    error: "Message",
    something_went_wrong: "Something went wrong",
    update: "Update",
    continue: "Continue",
    enter_verification_code: "Enter Verification Code",
    enter_new_password: "Please Enter New Password",
    update_password: "Update password",
    your_seesion_has_expired: "Your session has been expired! Please login again.",
    is_first_time_open: "isFirstTimeOpen"
}
